version: '3.8'

services:
  reactapp:
    build:
      context: .                     
      dockerfile: Dockerfile          
    ports:
      - "3000:3000"                    
    environment:
      - NODE_ENV=production             
    restart: always          
